### ISSUE TITLE
Start the Standard Library

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#17]
**Describe the solution you'd like**

A core standard library based on: https://clojuredocs.org/quickref

At the moment, a function body can only be a Rimu expression. But for a standard library, we need to be able to access things in Rust-land, such as the length of a list's vec. 

**TODO Checklist**

- [ ] Change `Value`'s `Function` into an enum
  - Existing case is `Function::Rimu`
  - New case is `Function::Rust`, where the enum references a Rust function.
- [ ] Create `rimu-stdlib` crate
  - [ ] Create `length` function

**Describe alternatives you've considered**

**Additional context**
