### ISSUE TITLE
MVP release TODO

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#31]
- [x] https://github.com/ahdinosaur/rimu/pull/1
- [x] https://github.com/ahdinosaur/rimu/pull/7
- [x] https://github.com/ahdinosaur/rimu/pull/8
- [x] https://github.com/ahdinosaur/rimu/pull/11
- [x] https://github.com/ahdinosaur/rimu/pull/15
- [x] https://github.com/ahdinosaur/rimu/pull/19
- [x] https://github.com/ahdinosaur/rimu/pull/28
- [x] https://github.com/ahdinosaur/rimu/pull/30
- [x] https://github.com/ahdinosaur/rimu/issues/3
- [x] https://github.com/ahdinosaur/rimu/issues/16
- [ ] https://github.com/ahdinosaur/rimu/issues/34
- [x] https://github.com/ahdinosaur/rimu/issues/29
- [x] https://github.com/ahdinosaur/rimu/issues/14
- [x] https://github.com/ahdinosaur/rimu/issues/17
- [x] https://github.com/ahdinosaur/rimu/issues/33 
- [x] https://github.com/ahdinosaur/rimu/issues/5
- [x] https://github.com/ahdinosaur/rimu/issues/6
